**Clustering Tipe Pengguna Media Sosial**

**Anggota Kelompok:**

1. Said Hasan Nasrallah (19250671) -Ketua 
2. Tata Dwi Tama Puta (19250729)
3. Shabryan Khaylani (19250936)
4. Hon Zie Kaori (19251001)
5. Sheren Putri Toisuta (19250707)

**Business Under standing**


**a. Latar belakang Pemilihan Dataset:**


Penggunaan media sosial telah menjadi bagian yang tidak terpisahkan dari kehidupan masyarakat modern. Namun, dibalik kemudahannya, penggunaan yang tidak terkontrol sering kali menimbulkan fenomena social media fatigue (kelelahan media sosial) dan menimbulkan dampak psikologis yang serius. Sebagaimana dinyatakan oleh (Putri & Aviani, 2023), "penggunaan media sosial yang intensif dapat memicu peningkatan gejala stres pada individu akibat adanya ketidaksesuaian antara ekspektasi digital dengan kenyataan hidup yang dialami.”

Masalah kesehatan mental seperti kecemasan, depresi, dan stres kini menjadi perhatian serius dalam interaksi digital. Data dari berbagai studi menunjukkan adanya keterkaitan antara durasi penggunaan, dan kondisi emosional pengguna. Namun, setiap individu memiliki pola perilaku yang berbeda-beda, ada yang tetap stabil meski aktif, namun ada juga yang sangat rentan meski durasi penggunaannya singkat.

Dalam konteks Data Science, pendekatan Unsupervised Learning melalui algoritma Clustering memberikan solusi untuk mengelompokkan karakteristik pengguna tanpa memerlukan pelabelan manual. Dengan memanfaatkan dataset "Social Media and Mental Health", penelitian ini bertujuan untuk mengidentifikasi segmen pengguna yang memiliki kerentanan tinggi terhadap gangguan mental. Hal ini sejalan dengan urgensi yang disampaikan oleh (Al Yasin, dkk., 2022), bahwa identifikasi dampak media sosial sangat penting sebagai langkah preventif untuk meminimalisir risiko kesehatan mental dan fisik jangka panjang.  Analisis ini diharapkan mampu memberikan kontribusi dalam memahami pola perilaku digital dan mendukung upaya preventif terhadap dampak negatif penggunaan media sosial secara berlebihan.


**b. Menjelaskan Type dan Informasi Data:**
Dari df.shape:
Dataset memiliki 481 baris (responden) dan 21 kolom (variabel/pertanyaan survei).

Dari df.info():
Dataset memiliki 2 tipe data yaitu:

Object (string/teks): Timestamp, Gender, Relationship Status, Occupation Status, Organizations, Do you use social media, Platforms used, dan Waktu harian (kolom 8) — total 8 kolom
Numerik (int64/float64): Usia (float64) dan kolom 9–20 skala 1–5 (int64) — total 13 kolom


Dari df.describe():
Kolom numerik skala 1–5 memiliki nilai minimum 1 dan maksimum 5. Rata-rata usia responden adalah 26 tahun, dengan usia termuda 13 tahun dan tertua 91 tahun.

Dari df.isnull().sum():
Hanya kolom "Organizations" yang memiliki 30 nilai kosong (missing value). Kolom lainnya tidak memiliki missing value.

Dari df.nunique():
Kolom "Platforms used" memiliki 125 kombinasi unik, artinya setiap responden menggunakan kombinasi platform yang sangat beragam sehingga kolom ini sulit diproses langsung.

**Data Preparation**

**a. Jelaskan tahapan apa saja yang digunakan pada tahap Data
Preparation:**

Ada 4 tahapan yang digunakan:

- Filtering data: hapus baris yang tidak relevan
- Seleksi fitur: buang kolom yang tidak dipakai clustering
- Encoding: ubah teks jadi angka
- Normalisasi: samain skala semua kolom


**b. Jelaskan hasil setiap tahapan yang digunakan**

Berdasarkan kode di notebook, ada 2 tahapan yang digunakan:

Menghapus kolom yang tidak relevan (Drop Columns)
Mengubah teks menjadi angka (Encoding)

**Tahap 1. Menghapus Kolom Tidak Relevan**

Kolom yang dihapus ada 4, yaitu:

- Timestamp: Hanya mencatat waktu pengisian form, tidak mencerminkan perilaku pengguna
- Organizations (kolom 5): Terdapat 30 missing value dan tidak relevan untuk clustering perilaku
- Platforms used (kolom 7): Berisi teks bebas dengan 125 kombinasi unik, tidak bisa langsung diolah
- Do you use social media? (kolom 6)Semua responden menjawab Yes/No, tidak berguna sebagai fitur clustering

Hasil: Dataset berkurang dari 21 kolom → 17 kolom. Kolom yang tersisa adalah data demografi (usia, gender, status) dan seluruh kolom perilaku + mental health skala 1–5 (kolom 8–20).

**Tahap 2. Encoding Kolom Waktu Harian**

Kolom 8 "Waktu harian di sosmed" masih berbentuk teks seperti "More than 5 hours" sehingga tidak bisa langsung diproses oleh algoritma. Kolom ini diubah ke angka menggunakan Ordinal Encoding karena nilainya memiliki urutan dari kecil ke besar.

In [1]:
import pandas as pd
file= "smmh.csv"
df=pd.read_csv(file)

In [2]:
print(f"Jumlah Baris dan Kolom di dataframe: {df.shape}")

Jumlah Baris dan Kolom di dataframe: (481, 21)

In [3]:
df.head(10)

,Timestamp,1. What is your age?,2. Gender,3. Relationship Status,4. Occupation Status,5. What type of organizations are you affiliated with?,6. Do you use social media?,7. What social media platforms do you commonly use?,8. What is the average time you spend on social media every day?,9. How often do you find yourself using Social media without a specific purpose?,...,11. Do you feel restless if you haven't used Social media in a while?,"12. On a scale of 1 to 5, how easily distracted are you?","13. On a scale of 1 to 5, how much are you bothered by worries?",14. Do you find it difficult to concentrate on things?,"15. On a scale of 1-5, how often do you compare yourself to other successful people through the use of social media?","16. Following the previous question, how do you feel about these comparisons, generally speaking?",17. How often do you look to seek validation from features of social media?,18. How often do you feel depressed or down?,"19. On a scale of 1 to 5, how frequently does your interest in daily activities fluctuate?","20. On a scale of 1 to 5, how often do you face issues regarding sleep?"
0,4/18/2022 19:18:47,21.0,Male,In a relationship,University Student,University,Yes,"Facebook, Twitter, Instagram, YouTube, Discord...",Between 2 and 3 hours,5,...,2,5,2,5,2,3,2,5,4,5
1,4/18/2022 19:19:28,21.0,Female,Single,University Student,University,Yes,"Facebook, Twitter, Instagram, YouTube, Discord...",More than 5 hours,4,...,2,4,5,4,5,1,1,5,4,5
2,4/18/2022 19:25:59,21.0,Female,Single,University Student,University,Yes,"Facebook, Instagram, YouTube, Pinterest",Between 3 and 4 hours,3,...,1,2,5,4,3,3,1,4,2,5
3,4/18/2022 19:29:43,21.0,Female,Single,University Student,University,Yes,"Facebook, Instagram",More than 5 hours,4,...,1,3,5,3,5,1,2,4,3,2
4,4/18/2022 19:33:31,21.0,Female,Single,University Student,University,Yes,"Facebook, Instagram, YouTube",Between 2 and 3 hours,3,...,4,4,5,5,3,3,3,4,4,1
5,4/18/2022 19:33:48,22.0,Female,Single,University Student,University,Yes,"Facebook, Twitter, Instagram, YouTube, Discord...",Between 2 and 3 hours,4,...,2,3,4,3,4,4,3,3,2,4
6,4/18/2022 19:36:12,21.0,Female,Married,University Student,University,Yes,"Facebook, Instagram, YouTube, Snapchat, TikTok",Between 3 and 4 hours,4,...,2,2,4,3,5,3,4,5,5,3
7,4/18/2022 19:36:17,21.0,Female,In a relationship,University Student,University,Yes,"Facebook, Instagram, YouTube",More than 5 hours,5,...,3,3,3,1,1,3,1,5,5,1
8,4/18/2022 19:39:36,21.0,Female,In a relationship,University Student,University,Yes,"Facebook, Instagram, YouTube",More than 5 hours,5,...,3,3,1,1,1,3,1,5,5,1
9,4/18/2022 19:41:34,20.0,Male,Single,University Student,University,No,"Reddit, Pinterest",Less than an Hour,1,...,1,1,1,1,1,1,1,1,1,1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 481 entries, 0 to 480
Data columns (total 21 columns):
 #   Column                                                                                                                Non-Null Count  Dtype
---  ------                                                                                                                --------------  -----
 0   Timestamp                                                                                                             481 non-null    object
 1   1. What is your age?                                                                                                  481 non-null    float64
 2   2. Gender                                                                                                             481 non-null    object
 3   3. Relationship Status                                                                                                481 non-null    object
 4   4. Occupation Status                                                                                                  481 non-null    object
 5   5. What type of organizations are you affiliated with?                                                                451 non-null    object
 6   6. Do you use social media?                                                                                           481 non-null    object
 7   7. What social media platforms do you commonly use?                                                                   481 non-null    object
 8   8. What is the average time you spend on social media every day?                                                      481 non-null    object
 9   9. How often do you find yourself using Social media without a specific purpose?                                      481 non-null    int64
 10  10. How often do you get distracted by Social media when you are busy doing something?                                481 non-null    int64
 11  11. Do you feel restless if you haven't used Social media in a while?                                                 481 non-null    int64
 12  12. On a scale of 1 to 5, how easily distracted are you?                                                              481 non-null    int64
 13  13. On a scale of 1 to 5, how much are you bothered by worries?                                                       481 non-null    int64
 14  14. Do you find it difficult to concentrate on things?                                                                481 non-null    int64
 15  15. On a scale of 1-5, how often do you compare yourself to other successful people through the use of social media?  481 non-null    int64
 16  16. Following the previous question, how do you feel about these comparisons, generally speaking?                     481 non-null    int64
 17  17. How often do you look to seek validation from features of social media?                                           481 non-null    int64
 18  18. How often do you feel depressed or down?                                                                          481 non-null    int64
 19  19. On a scale of 1 to 5, how frequently does your interest in daily activities fluctuate?                            481 non-null    int64
 20  20. On a scale of 1 to 5, how often do you face issues regarding sleep?                                               481 non-null    int64
dtypes: float64(1), int64(12), object(8)
memory usage: 79.0+ KB

In [5]:
df.describe()

,1. What is your age?,9. How often do you find yourself using Social media without a specific purpose?,10. How often do you get distracted by Social media when you are busy doing something?,11. Do you feel restless if you haven't used Social media in a while?,"12. On a scale of 1 to 5, how easily distracted are you?","13. On a scale of 1 to 5, how much are you bothered by worries?",14. Do you find it difficult to concentrate on things?,"15. On a scale of 1-5, how often do you compare yourself to other successful people through the use of social media?","16. Following the previous question, how do you feel about these comparisons, generally speaking?",17. How often do you look to seek validation from features of social media?,18. How often do you feel depressed or down?,"19. On a scale of 1 to 5, how frequently does your interest in daily activities fluctuate?","20. On a scale of 1 to 5, how often do you face issues regarding sleep?"
count,481.00000,481.000000,481.000000,481.000000,481.000000,481.000000,481.000000,481.000000,481.000000,481.000000,481.000000,481.000000,481.000000
mean,26.13659,3.553015,3.320166,2.588358,3.349272,3.559252,3.245322,2.831601,2.775468,2.455301,3.255717,3.170478,3.201663
std,9.91511,1.096299,1.328137,1.257059,1.175552,1.283356,1.347105,1.407835,1.056479,1.247739,1.313033,1.256666,1.461619
min,13.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,21.00000,3.000000,2.000000,2.000000,3.000000,3.000000,2.000000,2.000000,2.000000,1.000000,2.000000,2.000000,2.000000
50%,22.00000,4.000000,3.000000,2.000000,3.000000,4.000000,3.000000,3.000000,3.000000,2.000000,3.000000,3.000000,3.000000
75%,26.00000,4.000000,4.000000,3.000000,4.000000,5.000000,4.000000,4.000000,3.000000,3.000000,4.000000,4.000000,5.000000
max,91.00000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000

In [6]:
df.isnull().sum()

Timestamp                                                                                                                0
1. What is your age?                                                                                                     0
2. Gender                                                                                                                0
3. Relationship Status                                                                                                   0
4. Occupation Status                                                                                                     0
5. What type of organizations are you affiliated with?                                                                  30
6. Do you use social media?                                                                                              0
7. What social media platforms do you commonly use?                                                                      0
8. What is the average time you spend on social media every day?                                                         0
9. How often do you find yourself using Social media without a specific purpose?                                         0
10. How often do you get distracted by Social media when you are busy doing something?                                   0
11. Do you feel restless if you haven't used Social media in a while?                                                    0
12. On a scale of 1 to 5, how easily distracted are you?                                                                 0
13. On a scale of 1 to 5, how much are you bothered by worries?                                                          0
14. Do you find it difficult to concentrate on things?                                                                   0
15. On a scale of 1-5, how often do you compare yourself to other successful people through the use of social media?     0
16. Following the previous question, how do you feel about these comparisons, generally speaking?                        0
17. How often do you look to seek validation from features of social media?                                              0
18. How often do you feel depressed or down?                                                                             0
19. On a scale of 1 to 5, how frequently does your interest in daily activities fluctuate?                               0
20. On a scale of 1 to 5, how often do you face issues regarding sleep?                                                  0
dtype: int64

In [7]:
df.nunique()

Timestamp                                                                                                               480
1. What is your age?                                                                                                     46
2. Gender                                                                                                                 9
3. Relationship Status                                                                                                    4
4. Occupation Status                                                                                                      4
5. What type of organizations are you affiliated with?                                                                   18
6. Do you use social media?                                                                                               2
7. What social media platforms do you commonly use?                                                                     125
8. What is the average time you spend on social media every day?                                                          6
9. How often do you find yourself using Social media without a specific purpose?                                          5
10. How often do you get distracted by Social media when you are busy doing something?                                    5
11. Do you feel restless if you haven't used Social media in a while?                                                     5
12. On a scale of 1 to 5, how easily distracted are you?                                                                  5
13. On a scale of 1 to 5, how much are you bothered by worries?                                                           5
14. Do you find it difficult to concentrate on things?                                                                    5
15. On a scale of 1-5, how often do you compare yourself to other successful people through the use of social media?      5
16. Following the previous question, how do you feel about these comparisons, generally speaking?                         5
17. How often do you look to seek validation from features of social media?                                               5
18. How often do you feel depressed or down?                                                                              5
19. On a scale of 1 to 5, how frequently does your interest in daily activities fluctuate?                                5
20. On a scale of 1 to 5, how often do you face issues regarding sleep?                                                   5
dtype: int64

In [8]:
df.drop(columns=["Timestamp","5. What type of organizations are you affiliated with?","7. What social media platforms do you commonly use?","6. Do you use social media?"], inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 481 entries, 0 to 480
Data columns (total 17 columns):
 #   Column                                                                                                                Non-Null Count  Dtype
---  ------                                                                                                                --------------  -----
 0   1. What is your age?                                                                                                  481 non-null    float64
 1   2. Gender                                                                                                             481 non-null    object
 2   3. Relationship Status                                                                                                481 non-null    object
 3   4. Occupation Status                                                                                                  481 non-null    object
 4   8. What is the average time you spend on social media every day?                                                      481 non-null    object
 5   9. How often do you find yourself using Social media without a specific purpose?                                      481 non-null    int64
 6   10. How often do you get distracted by Social media when you are busy doing something?                                481 non-null    int64
 7   11. Do you feel restless if you haven't used Social media in a while?                                                 481 non-null    int64
 8   12. On a scale of 1 to 5, how easily distracted are you?                                                              481 non-null    int64
 9   13. On a scale of 1 to 5, how much are you bothered by worries?                                                       481 non-null    int64
 10  14. Do you find it difficult to concentrate on things?                                                                481 non-null    int64
 11  15. On a scale of 1-5, how often do you compare yourself to other successful people through the use of social media?  481 non-null    int64
 12  16. Following the previous question, how do you feel about these comparisons, generally speaking?                     481 non-null    int64
 13  17. How often do you look to seek validation from features of social media?                                           481 non-null    int64
 14  18. How often do you feel depressed or down?                                                                          481 non-null    int64
 15  19. On a scale of 1 to 5, how frequently does your interest in daily activities fluctuate?                            481 non-null    int64
 16  20. On a scale of 1 to 5, how often do you face issues regarding sleep?                                               481 non-null    int64
dtypes: float64(1), int64(12), object(4)
memory usage: 64.0+ KB

In [9]:
waktu_penggunaan = {
    'Less than an Hour': 1,
    'Between 1 and 2 hours': 1.8,
    'Between 2 and 3 hours': 2.6,
    'Between 3 and 4 hours': 3.4,
    'Between 4 and 5 hours': 4.2,
    'More than 5 hours': 5
}
df['8. What is the average time you spend on social media every day?'] = df['8. What is the average time you spend on social media every day?'].map(waktu_penggunaan)
df.head(10)

,1. What is your age?,2. Gender,3. Relationship Status,4. Occupation Status,8. What is the average time you spend on social media every day?,9. How often do you find yourself using Social media without a specific purpose?,10. How often do you get distracted by Social media when you are busy doing something?,11. Do you feel restless if you haven't used Social media in a while?,"12. On a scale of 1 to 5, how easily distracted are you?","13. On a scale of 1 to 5, how much are you bothered by worries?",14. Do you find it difficult to concentrate on things?,"15. On a scale of 1-5, how often do you compare yourself to other successful people through the use of social media?","16. Following the previous question, how do you feel about these comparisons, generally speaking?",17. How often do you look to seek validation from features of social media?,18. How often do you feel depressed or down?,"19. On a scale of 1 to 5, how frequently does your interest in daily activities fluctuate?","20. On a scale of 1 to 5, how often do you face issues regarding sleep?"
0,21.0,Male,In a relationship,University Student,2.6,5,3,2,5,2,5,2,3,2,5,4,5
1,21.0,Female,Single,University Student,5.0,4,3,2,4,5,4,5,1,1,5,4,5
2,21.0,Female,Single,University Student,3.4,3,2,1,2,5,4,3,3,1,4,2,5
3,21.0,Female,Single,University Student,5.0,4,2,1,3,5,3,5,1,2,4,3,2
4,21.0,Female,Single,University Student,2.6,3,5,4,4,5,5,3,3,3,4,4,1
5,22.0,Female,Single,University Student,2.6,4,4,2,3,4,3,4,4,3,3,2,4
6,21.0,Female,Married,University Student,3.4,4,3,2,2,4,3,5,3,4,5,5,3
7,21.0,Female,In a relationship,University Student,5.0,5,2,3,3,3,1,1,3,1,5,5,1
8,21.0,Female,In a relationship,University Student,5.0,5,2,3,3,1,1,1,3,1,5,5,1
9,20.0,Male,Single,University Student,1.0,1,1,1,1,1,1,1,1,1,1,1,1