In [42]:
import pandas as pd
file= "smmh.csv"
df=pd.read_csv(file)

In [43]:
print(f"Jumlah Baris dan Kolom di dataframe: {df.shape}")

Jumlah Baris dan Kolom di dataframe: (481, 21)

In [44]:
df.head(10)

,Timestamp,1. What is your age?,2. Gender,3. Relationship Status,4. Occupation Status,5. What type of organizations are you affiliated with?,6. Do you use social media?,7. What social media platforms do you commonly use?,8. What is the average time you spend on social media every day?,9. How often do you find yourself using Social media without a specific purpose?,...,11. Do you feel restless if you haven't used Social media in a while?,"12. On a scale of 1 to 5, how easily distracted are you?","13. On a scale of 1 to 5, how much are you bothered by worries?",14. Do you find it difficult to concentrate on things?,"15. On a scale of 1-5, how often do you compare yourself to other successful people through the use of social media?","16. Following the previous question, how do you feel about these comparisons, generally speaking?",17. How often do you look to seek validation from features of social media?,18. How often do you feel depressed or down?,"19. On a scale of 1 to 5, how frequently does your interest in daily activities fluctuate?","20. On a scale of 1 to 5, how often do you face issues regarding sleep?"
0,4/18/2022 19:18:47,21.0,Male,In a relationship,University Student,University,Yes,"Facebook, Twitter, Instagram, YouTube, Discord...",Between 2 and 3 hours,5,...,2,5,2,5,2,3,2,5,4,5
1,4/18/2022 19:19:28,21.0,Female,Single,University Student,University,Yes,"Facebook, Twitter, Instagram, YouTube, Discord...",More than 5 hours,4,...,2,4,5,4,5,1,1,5,4,5
2,4/18/2022 19:25:59,21.0,Female,Single,University Student,University,Yes,"Facebook, Instagram, YouTube, Pinterest",Between 3 and 4 hours,3,...,1,2,5,4,3,3,1,4,2,5
3,4/18/2022 19:29:43,21.0,Female,Single,University Student,University,Yes,"Facebook, Instagram",More than 5 hours,4,...,1,3,5,3,5,1,2,4,3,2
4,4/18/2022 19:33:31,21.0,Female,Single,University Student,University,Yes,"Facebook, Instagram, YouTube",Between 2 and 3 hours,3,...,4,4,5,5,3,3,3,4,4,1
5,4/18/2022 19:33:48,22.0,Female,Single,University Student,University,Yes,"Facebook, Twitter, Instagram, YouTube, Discord...",Between 2 and 3 hours,4,...,2,3,4,3,4,4,3,3,2,4
6,4/18/2022 19:36:12,21.0,Female,Married,University Student,University,Yes,"Facebook, Instagram, YouTube, Snapchat, TikTok",Between 3 and 4 hours,4,...,2,2,4,3,5,3,4,5,5,3
7,4/18/2022 19:36:17,21.0,Female,In a relationship,University Student,University,Yes,"Facebook, Instagram, YouTube",More than 5 hours,5,...,3,3,3,1,1,3,1,5,5,1
8,4/18/2022 19:39:36,21.0,Female,In a relationship,University Student,University,Yes,"Facebook, Instagram, YouTube",More than 5 hours,5,...,3,3,1,1,1,3,1,5,5,1
9,4/18/2022 19:41:34,20.0,Male,Single,University Student,University,No,"Reddit, Pinterest",Less than an Hour,1,...,1,1,1,1,1,1,1,1,1,1

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 481 entries, 0 to 480
Data columns (total 21 columns):
 #   Column                                                                                                                Non-Null Count  Dtype
---  ------                                                                                                                --------------  -----
 0   Timestamp                                                                                                             481 non-null    object
 1   1. What is your age?                                                                                                  481 non-null    float64
 2   2. Gender                                                                                                             481 non-null    object
 3   3. Relationship Status                                                                                                481 non-null    object
 4   4. Occupation Status                                                                                                  481 non-null    object
 5   5. What type of organizations are you affiliated with?                                                                451 non-null    object
 6   6. Do you use social media?                                                                                           481 non-null    object
 7   7. What social media platforms do you commonly use?                                                                   481 non-null    object
 8   8. What is the average time you spend on social media every day?                                                      481 non-null    object
 9   9. How often do you find yourself using Social media without a specific purpose?                                      481 non-null    int64
 10  10. How often do you get distracted by Social media when you are busy doing something?                                481 non-null    int64
 11  11. Do you feel restless if you haven't used Social media in a while?                                                 481 non-null    int64
 12  12. On a scale of 1 to 5, how easily distracted are you?                                                              481 non-null    int64
 13  13. On a scale of 1 to 5, how much are you bothered by worries?                                                       481 non-null    int64
 14  14. Do you find it difficult to concentrate on things?                                                                481 non-null    int64
 15  15. On a scale of 1-5, how often do you compare yourself to other successful people through the use of social media?  481 non-null    int64
 16  16. Following the previous question, how do you feel about these comparisons, generally speaking?                     481 non-null    int64
 17  17. How often do you look to seek validation from features of social media?                                           481 non-null    int64
 18  18. How often do you feel depressed or down?                                                                          481 non-null    int64
 19  19. On a scale of 1 to 5, how frequently does your interest in daily activities fluctuate?                            481 non-null    int64
 20  20. On a scale of 1 to 5, how often do you face issues regarding sleep?                                               481 non-null    int64
dtypes: float64(1), int64(12), object(8)
memory usage: 79.0+ KB

In [46]:
df.describe()

,1. What is your age?,9. How often do you find yourself using Social media without a specific purpose?,10. How often do you get distracted by Social media when you are busy doing something?,11. Do you feel restless if you haven't used Social media in a while?,"12. On a scale of 1 to 5, how easily distracted are you?","13. On a scale of 1 to 5, how much are you bothered by worries?",14. Do you find it difficult to concentrate on things?,"15. On a scale of 1-5, how often do you compare yourself to other successful people through the use of social media?","16. Following the previous question, how do you feel about these comparisons, generally speaking?",17. How often do you look to seek validation from features of social media?,18. How often do you feel depressed or down?,"19. On a scale of 1 to 5, how frequently does your interest in daily activities fluctuate?","20. On a scale of 1 to 5, how often do you face issues regarding sleep?"
count,481.00000,481.000000,481.000000,481.000000,481.000000,481.000000,481.000000,481.000000,481.000000,481.000000,481.000000,481.000000,481.000000
mean,26.13659,3.553015,3.320166,2.588358,3.349272,3.559252,3.245322,2.831601,2.775468,2.455301,3.255717,3.170478,3.201663
std,9.91511,1.096299,1.328137,1.257059,1.175552,1.283356,1.347105,1.407835,1.056479,1.247739,1.313033,1.256666,1.461619
min,13.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,21.00000,3.000000,2.000000,2.000000,3.000000,3.000000,2.000000,2.000000,2.000000,1.000000,2.000000,2.000000,2.000000
50%,22.00000,4.000000,3.000000,2.000000,3.000000,4.000000,3.000000,3.000000,3.000000,2.000000,3.000000,3.000000,3.000000
75%,26.00000,4.000000,4.000000,3.000000,4.000000,5.000000,4.000000,4.000000,3.000000,3.000000,4.000000,4.000000,5.000000
max,91.00000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000

In [47]:
df.isnull().sum()

Timestamp                                                                                                                0
1. What is your age?                                                                                                     0
2. Gender                                                                                                                0
3. Relationship Status                                                                                                   0
4. Occupation Status                                                                                                     0
5. What type of organizations are you affiliated with?                                                                  30
6. Do you use social media?                                                                                              0
7. What social media platforms do you commonly use?                                                                      0
8. What is the average time you spend on social media every day?                                                         0
9. How often do you find yourself using Social media without a specific purpose?                                         0
10. How often do you get distracted by Social media when you are busy doing something?                                   0
11. Do you feel restless if you haven't used Social media in a while?                                                    0
12. On a scale of 1 to 5, how easily distracted are you?                                                                 0
13. On a scale of 1 to 5, how much are you bothered by worries?                                                          0
14. Do you find it difficult to concentrate on things?                                                                   0
15. On a scale of 1-5, how often do you compare yourself to other successful people through the use of social media?     0
16. Following the previous question, how do you feel about these comparisons, generally speaking?                        0
17. How often do you look to seek validation from features of social media?                                              0
18. How often do you feel depressed or down?                                                                             0
19. On a scale of 1 to 5, how frequently does your interest in daily activities fluctuate?                               0
20. On a scale of 1 to 5, how often do you face issues regarding sleep?                                                  0
dtype: int64